// <auto-generated />
using CloneSAP_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloneSAP_API.Migrations
{
    [DbContext(typeof(SAPContext))]
    [Migration("20230503220909_stock id")]
    partial class stockid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CloneSAP_API.Models.Grid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CollorCod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SizeCod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grid");
                });

            modelBuilder.Entity("CloneSAP_API.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("material")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<float>("volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("CloneSAP_API.Models.StockID", b =>
                {
                    b.Property<int>("stockIDn")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(999999999)
                        .HasColumnType("int");

                    b.Property<int>("gridId1")
                        .HasColumnType("int");

                    b.Property<int>("materialId1")
                        .HasColumnType("int");

                    b.HasKey("stockIDn");

                    b.HasIndex("gridId1");

                    b.HasIndex("materialId1");

                    b.ToTable("StockID");
                });

            modelBuilder.Entity("CloneSAP_API.Models.StorageUnit", b =>
                {
                    b.Property<int>("SU")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<int>("stockIDn")
                        .HasColumnType("int");

                    b.HasKey("SU");

                    b.HasIndex("stockIDn");

                    b.ToTable("StorageUnit");
                });

            modelBuilder.Entity("CloneSAP_API.Models.StockID", b =>
                {
                    b.HasOne("CloneSAP_API.Models.Grid", "grid")
                        .WithMany()
                        .HasForeignKey("gridId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloneSAP_API.Models.Material", "material")
                        .WithMany()
                        .HasForeignKey("materialId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("grid");

                    b.Navigation("material");
                });

            modelBuilder.Entity("CloneSAP_API.Models.StorageUnit", b =>
                {
                    b.HasOne("CloneSAP_API.Models.StockID", "StockID")
                        .WithMany()
                        .HasForeignKey("stockIDn")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockID");
                });
#pragma warning restore 612, 618
        }
    }
}
