// <auto-generated />
using CloneSAP_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloneSAP_API.Migrations
{
    [DbContext(typeof(SAPContext))]
    [Migration("20230503193815_Grid linked material")]
    partial class Gridlinkedmaterial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CloneSAP_API.Models.Grid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CollorCod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SizeCod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grid");
                });

            modelBuilder.Entity("CloneSAP_API.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("gridId")
                        .HasColumnType("int");

                    b.Property<string>("material")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<float>("volume")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("gridId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("CloneSAP_API.Models.Material", b =>
                {
                    b.HasOne("CloneSAP_API.Models.Grid", "grid")
                        .WithMany()
                        .HasForeignKey("gridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("grid");
                });
#pragma warning restore 612, 618
        }
    }
}
